apiVersion: v1
kind: Service

metadata:
  name: local-llm-api
  namespace: ai-platform

  labels:
    app: local-llm-api
    app.kubernetes.io/name: local-llm-api

spec:
  type: ClusterIP

  selector:
    app: local-llm-api

  ports:
    - name: http
      protocol: TCP

      port: 80
      targetPort: http