apiVersion: v1
kind: Service
metadata:
  name: airflow-spark
  namespace: ai-platform
  labels:
    app: airflow-spark

spec:
  type: ClusterIP

  selector:
    app: airflow-spark

  ports:
    - name: web
      port: 8080
      targetPort: web

      #  Starting Airflow Standalone
# Simple auth manager | Password for user 'admin': 4mYsfFeny4cB7PdD