apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
  namespace: ai-platform
type: Opaque
stringData:
  POSTGRES_USER: "day03admin "
  POSTGRES_PASSWORD: "1234567890"
  POSTGRES_DB: "day03_platform"